- name: Build and Dockerize Next.js Application
  hosts: dockerservers
  gather_facts: true
  remote_user: root
  tasks:
    # First check and install curl
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    # Install Node.js and npm using nvm (more reliable method)
    - name: Download nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install Node.js and npm
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18
        nvm use 18
      args:
        executable: /bin/bash

    # Verify npm installation
    - name: Check npm version
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm --version
      register: npm_version
      args:
        executable: /bin/bash

    - debug:
        var: npm_version.stdout

    # Continue with your build process
    - name: Install Node.js dependencies
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd ~/66022365nextjs && npm ci
      args:
        executable: /bin/bash

    - name: Build Next.js application
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd ~/66022365nextjs && npm run build
      args:
        executable: /bin/bash
      environment:
        NODE_ENV: production
        NEXT_TELEMETRY_DISABLED: 1

    - name: Building Docker Image
      docker_image:
        name: 66022365nextjs:latest
        source: build
        build:
          path: ~/66022365nextjs
        state: present
        force_source: true