---
- name: Deploy Next.js Application
  hosts: dockerservers
  gather_facts: true
  remote_user: root
  
  tasks:
    # Stop existing container if running
    - name: Stop running container
      docker_container:
        name: nextjs-app
        state: stopped
      ignore_errors: yes

    # Remove old container
    - name: Remove container
      docker_container:
        name: nextjs-app
        state: absent
      ignore_errors: yes

    # Remove old image
    - name: Remove image
      docker_image:
        name: 66022365nextjs
        tag: latest
        state: absent
      ignore_errors: yes

    # Build new image
    - name: Build Docker Image
      docker_image:
        name: 66022365nextjs:latest
        source: build
        build:
          path: ~/66022365nextjs
        state: present
        force_source: true

    # Deploy new container
    - name: Run container
      docker_container:
        name: nextjs-app
        image: 66022365nextjs:latest
        state: started
        restart_policy: always
        ports:
          - "3333:3000"
        env:
          NODE_ENV: production